version: 0.2

phases:
  build:
    commands:
      - echo "Preparing website files for deployment..."
      
artifacts:
  base-directory: 'Project1/website'  # Specify your website folder here
  files:
    - '**/*'
  discard-paths: no